import { CONFIG } from '../config'
import { showError, showSuccess } from '../utils/notificationUtils'
import { Connection, LAMPORTS_PER_SOL, PublicKey } from '@solana/web3.js'

export interface DepositRequest {
  linkId: string
  amount: string
  publicKey: string
}

/**
 * ✅ USER-PAYS DEPOSIT FLOW - Frontend directly uses Privacy Cash SDK
 * 
 * NEW ARCHITECTURE - User has complete control:
 * 1. Frontend: Check user SOL balance
 * 2. Frontend: Initialize Privacy Cash SDK with USER's wallet (not operator!)
 * 3. Frontend: Call SDK.deposit(lamports) - generates proof internally
 * 4. Frontend: Phantom popup - user approves transaction
 * 5. Frontend: User signs transaction with their private key
 * 6. SDK: Submits transaction to blockchain (user pays all fees)
 * 7. Frontend: Get transaction signature
 * 8. Frontend: Send signature to backend to record
 * 9. Backend: Just records transaction in database
 * 
 * Result:
 * - User has full control and transparency
 * - No operator wallet required
 * - No operator wallet funding needed
 * - Zero-knowledge proofs generated by SDK
 * - All fees paid by user directly
 * - Most decentralized approach
 */
export async function executeUserPaysDeposit(
  request: DepositRequest,
  wallet: any
): Promise<string> {
  const { linkId, amount, publicKey } = request
  const lamports = Math.round(parseFloat(amount) * 1e9)

  console.log('\n🎯 USER-PAYS DEPOSIT - Privacy Cash on Frontend')
  console.log(`   ✅ You initialize SDK with YOUR wallet`)
  console.log(`   ✅ You sign transaction`)
  console.log(`   ✅ You pay all fees`)

  try {
    // ✅ STEP 1: Check user's SOL balance
    console.log('\n🔍 Step 1: Checking your SOL balance...')
    const userBalance = await checkUserBalance(wallet.publicKey)
    const userBalanceSOL = userBalance / LAMPORTS_PER_SOL

    console.log(`   Your wallet: ${publicKey}`)
    console.log(`   Your balance: ${userBalanceSOL.toFixed(6)} SOL`)

    // Estimate fees (~0.002 SOL)
    const estimatedFees = 2_000_000
    const totalNeeded = lamports + estimatedFees
    const totalNeededSOL = totalNeeded / LAMPORTS_PER_SOL

    if (userBalance < totalNeeded) {
      const shortfall = (totalNeeded - userBalance) / LAMPORTS_PER_SOL
      throw new Error(
        `❌ Insufficient balance:\n` +
        `You have ${userBalanceSOL.toFixed(6)} SOL\n` +
        `You need ${totalNeededSOL.toFixed(6)} SOL ` +
        `(${parseFloat(amount).toFixed(6)} SOL deposit + ~0.002 SOL fees)\n` +
        `Please add ${shortfall.toFixed(6)} SOL to your wallet`
      )
    }

    console.log(`   ✅ Balance sufficient for deposit\n`)

    // ✅ STEP 2: Initialize Privacy Cash SDK with USER's wallet
    console.log(`🚀 Step 2: Initializing Privacy Cash with YOUR wallet...`)
    console.log(`   SDK initialized with user wallet adapter`)
    console.log(`   User: ${publicKey.substring(0, 8)}...`)

    const { PrivacyCash } = await import('privacycash')

    // Create wallet adapter from Phantom wallet
    const walletAdapter = {
      publicKey: wallet.publicKey,
      signTransaction: wallet.signTransaction.bind(wallet),
      signAllTransactions: wallet.signAllTransactions.bind(wallet),
    }

    const rpcUrl = process.env.VITE_SOLANA_RPC_URL || CONFIG.SOLANA_RPC_URL || 
      'https://mainnet.helius-rpc.com/?api-key=c455719c-354b-4a44-98d4-27f8a18aa79c'

    // Initialize SDK with USER's wallet
    const privacyCashClient = new PrivacyCash({
      RPC_url: rpcUrl,
      owner: walletAdapter as any,  // USER's wallet, not operator!
      enableDebug: true,
    })

    console.log(`   ✅ Privacy Cash SDK initialized with your wallet\n`)

    // ✅ STEP 3: Generate ZK proof and transaction (SDK handles this)
    console.log(`🔐 Step 3: Generating zero-knowledge proof...`)
    console.log(`   Privacy Cash SDK is creating your proof`)
    console.log(`   This proves you have SOL without revealing wallet details`)

    // Call SDK to deposit - this handles:
    // - Generating ZK proof
    // - Creating transaction
    // - Asking Phantom to sign
    // - Submitting to blockchain
    const depositResult = await privacyCashClient.deposit({
      lamports: lamports,
    })

    console.log(`   ✅ Proof generated`)
    console.log(`   ✅ Transaction prepared\n`)

    // ✅ STEP 4: User signs transaction in Phantom
    console.log(`✍️  Step 4: Signing with Phantom...`)
    console.log(`   Phantom will ask you to approve`)
    console.log(`   You'll see your transaction details`)

    // Note: SDK.deposit() handles the Phantom signing automatically
    // The user sees the Phantom popup during the SDK.deposit() call above

    const transactionSignature = (depositResult as any)?.signature || (depositResult as any)?.tx || (depositResult as any)?.transactionHash || depositResult.tx

    if (!transactionSignature) {
      throw new Error('No transaction signature returned from Privacy Cash SDK')
    }

    console.log(`   ✅ Signed and submitted by SDK\n`)

    // ✅ STEP 5: Wait for blockchain confirmation
    console.log(`⏳ Step 5: Waiting for blockchain confirmation...`)

    const connection = new Connection(rpcUrl)

    let confirmation: any
    try {
      confirmation = await connection.confirmTransaction(transactionSignature, 'confirmed')

      if (confirmation.value.err) {
        throw new Error('Transaction failed on blockchain')
      }

      console.log(`   ✅ Confirmed on blockchain`)
    } catch (confirmErr) {
      console.log(`   ⚠️  Confirmation pending (might still be processing)`)
    }

    console.log(`   ✅ Block slot: ${confirmation?.context?.slot || 'pending'}\n`)

    // ✅ STEP 6: Record deposit with backend
    console.log(`💾 Step 6: Recording deposit with backend...`)

    const recordPayload = {
      linkId,
      transactionHash: transactionSignature,
      amount: amount.toString(),
      publicKey,
      lamports,
    }

    const recordResponse = await fetch(
      `${CONFIG.BACKEND_URL}/api/deposit`,
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(recordPayload),
      }
    )

    if (!recordResponse.ok) {
      const errorData = await recordResponse.json().catch(() => ({}))
      console.warn('⚠️  Backend recording warning:', errorData)
      // Don't fail here - transaction is on blockchain even if backend recording fails
    } else {
      console.log(`   ✅ Backend recorded transaction`)
    }

    console.log(`   ✅ Deposit recorded in database\n`)

    // ✅ SUCCESS
    console.log(`\n✨ DEPOSIT COMPLETE!\n`)
    console.log(`Amount: ${amount} SOL`)
    console.log(`Status: Confirmed on blockchain`)
    console.log(`Privacy: Zero-knowledge encrypted`)
    console.log(`You paid: ~${formatSOL(lamports)} SOL + transaction fees`)
    console.log(`Your wallet: ${publicKey}`)
    console.log(`Transaction: ${transactionSignature}`)
    console.log(`Explorer: ${getExplorerUrl(transactionSignature)}`)

    showSuccess(
      `✨ Deposit Complete!\n\n` +
      `Amount: ${amount} SOL\n` +
      `Status: Confirmed on blockchain\n` +
      `Privacy: Zero-knowledge encrypted\n\n` +
      `You paid: ~${formatSOL(lamports)} SOL + network fees\n` +
      `Your wallet signed the transaction\n\n` +
      `View transaction:\n${getExplorerUrl(transactionSignature)}`
    )

    return transactionSignature

  } catch (error: any) {
    console.error('\n❌ DEPOSIT FAILED:', error.message)
    console.error('Full error:', error)

    let errorMsg = error.message || 'Unknown error'

    // User-friendly error messages
    if (error.message?.toLowerCase().includes('user rejected') || 
        error.message?.includes('rejected')) {
      errorMsg = 'You rejected the transaction in Phantom.\nPlease try again and click "Approve".'
    } else if (error.message?.toLowerCase().includes('insufficient')) {
      errorMsg = error.message
    } else if (error.message?.includes('network') || error.message?.includes('connection')) {
      errorMsg = 'Network error. Please check your connection and try again.'
    } else if (error.message?.includes('timeout')) {
      errorMsg = 'Request timed out. Please try again.'
    } else if (error.message?.includes('balance')) {
      errorMsg = 'Insufficient balance. Add more SOL to your wallet and try again.'
    } else if (error.message?.includes('SDK') || error.message?.includes('Privacy Cash')) {
      errorMsg = 'Privacy Cash SDK error. Please try again or contact support.'
    }

    showError(`❌ Deposit failed:\n${errorMsg}`)
    throw new Error(errorMsg)
  }
}

/**
 * Helper: Check user's SOL balance
 */
async function checkUserBalance(publicKey: PublicKey): Promise<number> {
  try {
    const rpcUrl = process.env.VITE_SOLANA_RPC_URL || CONFIG.SOLANA_RPC_URL || 
      'https://mainnet.helius-rpc.com/?api-key=c455719c-354b-4a44-98d4-27f8a18aa79c'
    
    const connection = new Connection(rpcUrl)
    const balance = await connection.getBalance(publicKey)
    return balance
  } catch (error) {
    console.error('Error checking balance:', error)
    throw new Error('Could not check wallet balance')
  }
}

/**
 * Helper: Format lamports to SOL
 */
export function formatSOL(lamports: number): string {
  return (lamports / LAMPORTS_PER_SOL).toFixed(6)
}

/**
 * Helper: Get Solana Explorer URL for transaction
 */
export function getExplorerUrl(transactionSignature: string): string {
  return `https://solscan.io/tx/${transactionSignature}`
}

// Export for backward compatibility
export const executeRealDeposit = executeUserPaysDeposit
